### ISSUE TITLE
Problem wenn Element Großansicht aktiviert hat

### ISSUE THREAD

**Issue by Kahmoon** [psi-4ward/glossary#10]
Hallo :-)

Ich mach hier mal ein Issue zur Erweiterung auf. Und zwar läuft gar nichts mehr wenn ein Glossarbild die Option Großansicht aktiv hat. Folgender Fehler wird angezeigt:

Fatal error: Call to undefined method stdClass::getName() in /homepages/46/d346729057/htdocs/xxxx/system/modules/core/library/Contao/Controller.php on line 2628

https://community.contao.org/de/showthread.php?55683-glossary-Fehler-wenn-Lightbox-aktiviert-ist

Allerdings muss ich dazu sagen das hier Contao 3.4.4 im Einsatz ist, weil der Kunde ein Update haben wollte. 

VG
Frank

**Comment by psi-4ward** [comment]
Hast du keinen Stacktrace für mich?

**Comment by Kahmoon** [comment]
Bitte was? :-). Wenn du mir sagst was das ist, schaue ich ob ich das liefern kann.

VG
Frank

**Comment by psi-4ward** [comment]
Testen!

**Comment by Kahmoon** [comment]
Voll gut! Das wars! Danke!

**Comment by psi-4ward** [comment]
Bitte wirklich n genauen Test fahren, dann Tagge ich ne neue Version

**Comment by Kahmoon** [comment]
Ich kann ohne Probleme neue Elemente anlegen (ging vorher schon) und die Großansicht öffnet sich jetzt auch in der Lightbox. Sowohl bei Abkürzung als auch Definition funktioniert es soweit bei mir.
