### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by cgpro** [psi-4ward/glossary#12]
Hi,

I've migrated to Contao 3.5 and PHP7 and fixed the frontend output temporarily:

In Listing.php in line 66 - 77

if ($GLOBALS['objPage']->outputFormat == 'xhtml')
{
	$objTerm->definition = \StringUtil::toXhtml($objTerm->definition);
}
else
{
	$objTerm->definition = \StringUtil::toHtml5($objTerm->definition);
}
$objTemp->definition = \StringUtil::encodeEmail($objTerm->definition);

Maybe useful for a quick fix for somebody.

**Comment by psi-4ward** [comment]
Nice! Can you prepare a pull request?
